url = "https://api.weather.test:9000/v2/forecast?city=Izmir&days=3#top"

# Take it apart with urlparse and print the parts:
# scheme: ...
# host: ...
# port: ...
# path: ...
# query: ...
# fragment: ...
