-- Bring back the products that satisfy all three:
--   category is Accessory or Display,
--   price is between 200 and 2000 (both ends included),
--   supplier_code is not empty.
-- Columns: name, category, price. Sort expensive to cheap.
