-- Su uc kosulu birden saglayan urunleri getir:
--   kategorisi Accessory ya da Display,
--   fiyati 200 ile 2000 arasinda (iki uc dahil),
--   supplier_code sutunu bos degil.
-- Sutunlar: name, category, price. Pahalidan ucuza sirala.
