-- Su uc kosulu birden saglayan urunleri getir:
--   kategorisi Aksesuar ya da Ekran,
--   fiyati 200 ile 2000 arasinda (iki uc dahil),
--   tedarikci_kod sutunu bos degil.
-- Sutunlar: ad, kategori, fiyat. Pahalidan ucuza sirala.
